application: tusdiputados
version: 1
runtime: python
api_version: 1

handlers:

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  #login: admin
  
- url: /images
  static_dir: images
  
- url: /js
  static_dir: js

- url: /styles
  static_dir: styles
  
- url: .*
  script: main.py

